namespace TruckConnect
{
	public class Metadata
	{
		public TelemetryType TelemetryType { get; init; }

		public TelemetryID ID { get; init; }

		public bool ConstantSize { get; init; }

		public UInt32 MasterOffset { get; init; }

		public UInt32 StructureOffset { get; init; }

		private string _macro = "";
		public string Macro
		{
			get => TelemetryType != TelemetryType.Structure ? _macro : throw new InvalidOperationException("This property is not available on structures.");
			init => _macro = TelemetryType != TelemetryType.Structure ? value : throw new InvalidOperationException("This property is not available on structures.");
		}

		private bool _indexed = false;
		public bool Indexed
		{
			get => TelemetryType != TelemetryType.Structure ? _indexed : throw new InvalidOperationException("This property is not available on structures.");
			init => _indexed = TelemetryType != TelemetryType.Structure ? value : throw new InvalidOperationException("This property is not available on structures.");
		}

		private UInt32 _maxCount = 0;
		public UInt32 MaxCount
		{
			get => TelemetryType == TelemetryType.Channel ? _maxCount : throw new InvalidOperationException("This property is only available for channels.");
			init => _maxCount = TelemetryType == TelemetryType.Channel ? value : throw new InvalidOperationException("This property is only available for channels.");
		}

		private bool _trailerChannel = false;
		public bool TrailerChannel
		{
			get => TelemetryType == TelemetryType.Channel ? _trailerChannel : throw new InvalidOperationException("This property is only available for channels.");
			init => _trailerChannel = TelemetryType == TelemetryType.Channel ? value : throw new InvalidOperationException("This property is only available for channels.");
		}

		private SCSValueType _valueType = SCSValueType.SCS_VALUE_TYPE_INVALID;
		public SCSValueType SCSValueType
		{
			get => TelemetryType == TelemetryType.Channel ? _valueType : throw new InvalidOperationException("This property is only available for channels.");
			init => _valueType = TelemetryType == TelemetryType.Channel ? value : throw new InvalidOperationException("This property is only available for channels.");
		}

		private bool _customChannel = false;
		public bool CustomChannel
		{
			get => TelemetryType == TelemetryType.Channel ? _customChannel : throw new InvalidOperationException("This property is only available for channels.");
			init => _customChannel = TelemetryType == TelemetryType.Channel ? value : throw new InvalidOperationException("This property is only available for channels.");
		}

		public static Metadata ByID(TelemetryID id) => Array.Find(METADATA, metadata => metadata.ID == id) ?? throw new ArgumentException("Metadata not found", nameof(id));

		public static readonly Metadata[] METADATA =
		[
			new() { ID = TelemetryID.Master, TelemetryType = TelemetryType.Structure, ConstantSize = false, MasterOffset = 0, StructureOffset = 0 },
			new() { ID = TelemetryID.Configuration, TelemetryType = TelemetryType.Structure, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0 /*?*/ },
			new() { ID = TelemetryID.Gameplay, TelemetryType = TelemetryType.Structure, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0 /*?*/ },
			new() { ID = TelemetryID.Channels, TelemetryType = TelemetryType.Structure, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0 /*?*/ },
			new() { ID = TelemetryID.General, TelemetryType = TelemetryType.Structure, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0 /*?*/ },
			new() { ID = TelemetryID.Truck, TelemetryType = TelemetryType.Structure, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0 /*?*/ },
			new() { ID = TelemetryID.Trailer, TelemetryType = TelemetryType.Structure, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0 /*?*/ },
			new() { ID = TelemetryID.ConfigurationSubstancesInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "substances" },
			new() { ID = TelemetryID.ConfigurationControlsInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "controls" },
			new() { ID = TelemetryID.ConfigurationHshifterInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "hshifter" },
			new() { ID = TelemetryID.ConfigurationTruckInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck" },
			new() { ID = TelemetryID.ConfigurationTrailerInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer" },
			new() { ID = TelemetryID.ConfigurationJobInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "job" },
			new() { ID = TelemetryID.GameplayJobCancelledInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "job.cancelled" },
			new() { ID = TelemetryID.GameplayJobDeliveredInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "job.delivered" },
			new() { ID = TelemetryID.GameplayPlayerFinedInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "player.fined" },
			new() { ID = TelemetryID.GameplayPlayerTollgatePaidInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "player.tollgate.paid" },
			new() { ID = TelemetryID.GameplayPlayerUseFerryInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "player.use.ferry" },
			new() { ID = TelemetryID.GameplayPlayerUseTrainInfo, TelemetryType = TelemetryType.EventInfo, ConstantSize = false, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "player.use.train" },
			new() { ID = TelemetryID.ChannelPaused, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.ChannelLocalScale, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "local.scale", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.ChannelGameTime, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "game.time", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_u32, CustomChannel = false},
			new() { ID = TelemetryID.ChannelMultiplayerTimeOffset, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "multiplayer.time.offset", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_s32, CustomChannel = false},
			new() { ID = TelemetryID.ChannelNextRestStop, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "rest.stop", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_s32, CustomChannel = false},
			new() { ID = TelemetryID.JobChannelCargoDamage, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "job.cargo.damage", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelConnected, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.connected", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelCargoDamage, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.cargo.damage", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWorldPlacement, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.world.placement", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_dplacement, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelLocalLinearVelocity, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.velocity.linear", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelLocalAngularVelocity, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.velocity.angular", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelLocalLinearAcceleration, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.acceleration.linear", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelLocalAngularAcceleration, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.acceleration.angular", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWearBody, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wear.body", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWearChassis, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wear.chassis", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWearWheels, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wear.wheels", Indexed = false, MaxCount = 1 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWheelSuspDeflection, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wheel.suspension.deflection", Indexed = true, MaxCount = 19 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWheelOnGround, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wheel.on_ground", Indexed = true, MaxCount = 19 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWheelSubstance, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wheel.substance", Indexed = true, MaxCount = 19 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_u32, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWheelVelocity, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wheel.angular_velocity", Indexed = true, MaxCount = 19 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWheelSteering, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wheel.steering", Indexed = true, MaxCount = 19 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWheelRotation, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wheel.rotation", Indexed = true, MaxCount = 19 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWheelLift, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wheel.lift", Indexed = true, MaxCount = 19 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TrailerChannelWheelLiftOffset, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "trailer.wheel.lift.offset", Indexed = true, MaxCount = 19 ,TrailerChannel = true, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWorldPlacement, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.world.placement", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_dplacement, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLocalLinearVelocity, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.local.velocity.linear", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLocalAngularVelocity, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.local.velocity.angular", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLocalLinearAcceleration, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.local.acceleration.linear", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLocalAngularAcceleration, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.local.acceleration.angular", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelCabinOffset, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.cabin.offset", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fplacement, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelCabinAngularVelocity, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.cabin.velocity.angular", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelCabinAngularAcceleration, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.cabin.acceleration.angular", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fvector, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelHeadOffset, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.head.offset", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_fplacement, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelSpeed, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.speed", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelEngineRpm, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.engine.rpm", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelEngineGear, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.engine.gear", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_s32, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelDisplayedGear, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.displayed.gear", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_s32, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelInputSteering, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.input.steering", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelInputThrottle, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.input.throttle", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelInputBrake, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.input.brake", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelInputClutch, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.input.clutch", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelEffectiveSteering, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.effective.steering", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelEffectiveThrottle, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.effective.throttle", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelEffectiveBrake, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.effective.brake", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelEffectiveClutch, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.effective.clutch", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelCruiseControl, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.cruise_control", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelHshifterSlot, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.hshifter.slot", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_u32, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelHshifterSelector, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.hshifter.select", Indexed = true, MaxCount = 2 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelParkingBrake, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.brake.parking", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelMotorBrake, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.brake.motor", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelRetarderLevel, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.brake.retarder", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_u32, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelBrakeAirPressure, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.brake.air.pressure", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelBrakeAirPressureWarning, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.brake.air.pressure.warning", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelBrakeAirPressureEmergency, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.brake.air.pressure.emergency", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelBrakeTemperature, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.brake.temperature", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelFuel, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.fuel.amount", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelFuelWarning, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.fuel.warning", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelFuelAverageConsumption, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.fuel.consumption.average", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelFuelRange, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.fuel.range", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelAdblue, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.adblue", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelAdblueWarning, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.adblue.warning", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelOilPressure, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.oil.pressure", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelOilPressureWarning, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.oil.pressure.warning", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelOilTemperature, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.oil.temperature", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWaterTemperature, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.water.temperature", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWaterTemperatureWarning, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.water.temperature.warning", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelBatteryVoltage, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.battery.voltage", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelBatteryVoltageWarning, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.battery.voltage.warning", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelElectricEnabled, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.electric.enabled", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelEngineEnabled, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.engine.enabled", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLblinker, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.lblinker", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelRblinker, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.rblinker", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelHazardWarning, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.hazard.warning", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightLblinker, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.lblinker", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightRblinker, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.rblinker", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightParking, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.parking", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightLowBeam, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.beam.low", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightHighBeam, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.beam.high", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightAuxFront, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.aux.front", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_u32, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightAuxRoof, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.aux.roof", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_u32, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightBeacon, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.beacon", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightBrake, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.brake", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLightReverse, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.light.reverse", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWipers, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wipers", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelDashboardBacklight, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.dashboard.backlight", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelDifferentialLock, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.differential_lock", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLiftAxle, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.lift_axle", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelLiftAxleIndicator, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.lift_axle.indicator", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelTrailerLiftAxle, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.trailer.lift_axle", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelTrailerLiftAxleIndicator, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.trailer.lift_axle.indicator", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWearEngine, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wear.engine", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWearTransmission, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wear.transmission", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWearCabin, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wear.cabin", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWearChassis, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wear.chassis", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWearWheels, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wear.wheels", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelOdometer, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.odometer", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelNavigationDistance, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.navigation.distance", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelNavigationTime, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.navigation.time", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelNavigationSpeedLimit, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.navigation.speed.limit", Indexed = false, MaxCount = 1 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWheelSuspDeflection, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wheel.suspension.deflection", Indexed = true, MaxCount = 14 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWheelOnGround, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wheel.on_ground", Indexed = true, MaxCount = 14 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_bool, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWheelSubstance, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wheel.substance", Indexed = true, MaxCount = 14 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_u32, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWheelVelocity, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wheel.angular_velocity", Indexed = true, MaxCount = 14 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWheelSteering, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wheel.steering", Indexed = true, MaxCount = 14 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWheelRotation, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wheel.rotation", Indexed = true, MaxCount = 14 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWheelLift, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wheel.lift", Indexed = true, MaxCount = 14 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false},
			new() { ID = TelemetryID.TruckChannelWheelLiftOffset, TelemetryType = TelemetryType.Channel, ConstantSize = true, MasterOffset = 0, /*?*/ StructureOffset = 0, /*?*/ Macro = "truck.wheel.lift.offset", Indexed = true, MaxCount = 14 ,TrailerChannel = false, SCSValueType = TruckConnect.SCSValueType.SCS_VALUE_TYPE_float, CustomChannel = false}
		];
	}
}

