#pragma once
#include "truckconnect_version.h"
#include "truckconnect_platform.h"
#include "value_storage.h"
#include "master_structure.h"
#include "telemetry_metadata.h"
#include "metadata_functions.h"
#include "packed_size.h"
#include "size_of_scs_type.h"
#include "storage_type_of.h"
#include "byte_converters.h"
#include "vector_collector.h"
#include "data.h"
#include "connection.h"

